version: '3'
services:
  client:
    # Step 5.1 - Point build step to the client directory
    build: 'frontend'
    ports:
      # Step 5.2 - Add the port that the client application runs on - (port:port).
      - '3000:3000'
    depends_on:
      - server
      - postgres
  server:
    # Step 5.3 - Point build step to the server directory

    build: 'backend'
    ports:
      # Step 5.4 - Add the port that the server application runs on - (port:port).
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/var/lib/postgresql/data
