version: '3'
services:
  client:
    # Step 5.1 - Point build step to the client directory
    build: 'frontend'
    ports:
      # Step 5.2 - Add the port that the client application runs on - (port:port).
      - '3000:3000'
    depends_on:
      - strapi
      - postgres
  # server:
  #   # Step 5.3 - Point build step to the server directory

  #   build: 'backend'
  #   ports:
  #     # Step 5.4 - Add the port that the server application runs on - (port:port).
  #     - '1337:1337'
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/var/lib/postgresql/data
  strapi:
    build: 'backend'
    container_name: strapirestaurantz
    restart: unless-stopped
    env_file: .env
    environment:
      # Using Variable Subtitution to obtain environment variables. For more : https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution.
      NODE_ENV: ${NODE_ENV:-development}
      # == MongoDB Atlas configuration ==
      DATABASE_CLIENT: postgres
      DATABASE_HOST: ${DATABASE_HOST:-127.0.0.1}
      DATABASE_SRV: ${DATABASE_SRV:-true}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-posgres}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-jamedrano}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_SSL: ${DATABASE_SSL:-false}
      # AUTHENTICATION_DATABASE: admin
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - '${PORT:-1337}:${PORT:-1337}'
    depends_on:
      - postgres
