version: '3'
services:
  strapi:
    build: .
    container_name: strapirestaurant
    restart: unless-stopped
    env_file: .env
    environment:
      # Using Variable Subtitution to obtain environment variables. For more : https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution.
      NODE_ENV: ${NODE_ENV:-development}
      # == MongoDB Atlas configuration ==
      DATABASE_CLIENT: postgres
      DATABASE_HOST: ${DATABASE_HOST:-127.0.0.1}
      DATABASE_SRV: ${DATABASE_SRV:-true}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-posgres}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-jarrodmedrano}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_SSL: ${DATABASE_SSL:-false}
      # AUTHENTICATION_DATABASE: admin
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - '${PORT:-1337}:${PORT:-1337}'
    volumes:
      - ./app:/srv/app
